name: API tests with .NET + TestContainers

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  local_development:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - run: dotnet restore 
      - name: Install test SDK dependencies
        run: dotnet tool install --global dotnet-suggest
      - name: Install .NET Test SDK
        run: dotnet add package Microsoft.NET.Test.Sdk --version 17.11.1
      - run: dotnet test --verbosity detailed
